# Generated by Django 3.0.7 on 2020-06-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch_APP', '0002_auto_20200618_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='comany',
            new_name='company',
        ),
    ]
